# Generated by Django 2.1.2 on 2018-10-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.TextField(unique=True, verbose_name='Componente activo')),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre de marca')),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componente-activo+', to='rest.Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.TextField(verbose_name='Presentacion')),
                ('registro', models.TextField(verbose_name='Registro sanitario')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formato', to='rest.Medicina')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(unique=True, verbose_name='Link')),
                ('clasificacion', models.TextField(verbose_name='Clasificacion')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medicina', to='rest.Medicina')),
            ],
        ),
    ]
