# Generated by Django 2.1.2 on 2018-12-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_tweet_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='nombre',
            field=models.TextField(unique=True, verbose_name='Nombre de marca'),
        ),
    ]
