# Generated by Django 2.1.2 on 2018-12-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20181218_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='nombre',
            field=models.TextField(verbose_name='Nombre de marca'),
        ),
    ]
