# Generated by Django 2.1.2 on 2018-11-04 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.TextField(unique=True, verbose_name='Componente activo')),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre de marca')),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componente-activo+', to='stores.Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.TextField(verbose_name='Presentacion')),
                ('registro', models.TextField(verbose_name='Registro sanitario')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formato', to='stores.Medicina')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosPorTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.IntegerField(verbose_name='Disponibilidad')),
                ('fechaDeIngreso', models.DateTimeField(verbose_name='Fecha de actualizacion')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med', to='stores.Presentacion')),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
