# Generated by Django 2.1.2 on 2018-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='registro',
        ),
        migrations.AlterField(
            model_name='productosportienda',
            name='fechaDeIngreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
